### ISSUE TITLE
fix: Non ASCII characters in the file path

### ISSUE THREAD

**Issue by Eliote** [alnitak/flutter_soloud#109]
When you try to load a file with a non-ascii character, the lib throws a "file not found" error.
Example:
```dart
await SoLoud.instance.loadFile("D:\Motörhead - 01 Ace of Spades.mp3", mode: LoadMode.memory);
```
```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SoLoudFileNotFoundException: The file was not found (on the C++ side).
#0      SoLoud.loadFile (package:flutter_soloud/src/soloud.dart:600:7)
<asynchronous suspension>
#1      _MainPageState._loadFile (package:eliote_player/main_page.dart:145:14)
<asynchronous suspension>
#2      _MainPageState._play (package:eliote_player/main_page.dart:274:17)
<asynchronous suspension>
```
If I change the name of the file to `Motorhead - 01 Ace of Spades.mp3` without the `ö`, it works.
Tested on Windows 11.

**Comment by Eliote** [comment]
That fixed it, thanks!

One thing I notice in the `main` branch is that when loading some big files (or probably due to slow io) the UI is now freezing. In the version 2.0.2 it worked as expected, the Future just took it's time to complete, without freezing the UI.
Is there something new I need to do/know or should I open another issue?

**Comment by alnitak** [comment]
> One thing I notice in the `main` branch is that when loading some big files (or probably due to slow io) the UI is now freezing. In the version 2.0.2 it worked as expected, the Future just took it's time to complete, without freezing the UI.
> Is there something new I need to do/know or should I open another issue?

Thank you @Eliote, that was a bug. No need for a new issue, I already did a PR and merged the fix if you want to try! Unfortunately on the web, there is still this (known) bug.

**Comment by Eliote** [comment]
Awesome, thank you!
