### ISSUE TITLE
More pub.dev points

### ISSUE THREAD

**Issue by guyluz11** [alnitak/flutter_soloud#11]
Let's get more points in pub.dev by following the flutter analysis 

![image](https://github.com/alnitak/flutter_soloud/assets/9304740/18cdf63d-5b74-4abe-886a-a65a5ec86bea)

**Comment by alnitak** [comment]
No need for PRs to fix Dart format analisys

**Comment by guyluz11** [comment]
Please explain why there is no need to fix this
