### ISSUE TITLE
feat: loadUrl adds headers parameter

### ISSUE THREAD

**Issue by biner88** [alnitak/flutter_soloud#115]
**Description**

Some playback links require header authentication

**Requirements**

- [ ] add headers

**Additional Context**
```
Future<AudioSource> loadUrl(
    String url,
    LoadMode mode, {
    http.Client? httpClient,
    Map<String, String>? headers,
  })
```

**Comment by misterfourtytwo** [comment]
you should be able to provide headers through `http.Client` configuration, nope?
