### ISSUE TITLE
feat: Load Error messages should propagate from C++ to Dart

### ISSUE THREAD

**Issue by filiph** [alnitak/flutter_soloud#127]
**Description**

When SoLoud isn't able to parse an audio file (e.g. because it's corrupted), the error message in Dart land should have as much context as possible. Currently, if an audio file is corrupted, we get this error:

```
SoLoudFileLoadFailedException: The file was found, but could not be loaded (on the C++ side).
```

I'm not sure if this is the case, but if the C++ side has any additional info about the error (such as "MP3 file missing metadata" or whatever), it would be great to surface this in Dart (and therefore in crash reports).

Alternatively, maybe let's just change the error message to something that sheds more light on what this error means. "File was found but could not be loaded" seems cryptic. Maybe add something like "(could be a permission error or the file is corrupted)".

**Requirements**

- [x] Trying to load a corrupted file is reported as such

**Additional Context**

I saw the `SoLoudFileLoadFailedException` error and thought it's a permission error or something like that. Instead, it was a file corruption error (the file was in Git LFS and so the "mp3" file just had a single line of text in it).

**Comment by alnitak** [comment]
Hi @filiph,

The loading method could raise `PlayerErrors.fileLoadFailed`, `PlayerErrors.fileNotFound`, or `PlayerErrors.outOfMemory`.
No other checks for errors like "missing metadata" are available on SoLoud lib.

Following your suggestion, I just updated the error text and tested a broken audio file.
