### ISSUE TITLE
iOS build fails with: Semantic Issue (Xcode): 'path' is unavailable: introduced in iOS 13.0

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [alnitak/flutter_soloud#128]
First things first: Thank you very much for providing flutter_soloud.

**Description**

Trying to run an app with flutter_soloud version 2.1.3 on iOS (17.5.1) fails with:
```
Launching lib/main.dart on Somebody’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXX
Xcode build done.                                           19.3s
Failed to build iOS app
Could not build the precompiled application for the device.
Semantic Issue (Xcode): 'path' is unavailable: introduced in iOS 13.0
/Users/.../ios/.symlinks/plugins/flutter_soloud/src/bindings.cpp:250:25

Semantic Issue (Xcode): 'u8path<char *>' is unavailable: introduced in iOS 13.0
/Users/.../ios/.symlinks/plugins/flutter_soloud/src/bindings.cpp:250:52

Semantic Issue (Xcode): '~path' is unavailable: introduced in iOS 13.0
/Users/.../ios/.symlinks/plugins/flutter_soloud/src/bindings.cpp:250:35

Semantic Issue (Xcode): '~path' is unavailable: introduced in iOS 13.0
/Users/.../ios/.symlinks/plugins/flutter_soloud/src/bindings.cpp:250:30

Semantic Issue (Xcode): 'string' is unavailable: introduced in iOS 13.0
/Users/.../ios/.symlinks/plugins/flutter_soloud/src/bindings.cpp:254:44
2

Error launching application on Sombody’s iPad.

Exited (1).
```

**Additional Context**

Looks like this got introduced in version 2.1.0. Version 2.0.2 builds just fine on iOS.

**Comment by alnitak** [comment]
I do not have a Mac to try and help with this, but I see that the errors complain about iOS 13.
Can you please try to modify the line:
```s.platform = :ios, '11.0'``
and change `11` to 13` in `ios/flutter_soloud.podspec`?

**Comment by FluffyBunniesTasteTheBest** [comment]
Thanks for the quick response!
Unfortunately the same with `s.platform = :ios, '13.0'` in `pub.dev/flutter_soloud-2.1.2/ios/flutter_soloud.podspec`

**Comment by dumabg** [comment]
In your Flutter project, check the ios/Runner.xcodeproj/project.pbxproj file for any deployment target settings. Look for lines like:

IPHONEOS_DEPLOYMENT_TARGET = 13.0;

**Comment by alnitak** [comment]
@FluffyBunniesTasteTheBest can you please try what @dumabg suggests?
I also tried on a hackintosh whit `s.platform = :ios, '13.0'` and after a `flutter clean` it compiled successfully (although I cannot run the app).

**Comment by dumabg** [comment]
Flutter app uses Impeller, that needs a GPU support. In a hackintosh doesn't run. But you can pass the parameter --no-enable-impeller to run it:

`flutter run --no-enable-impeller`

**Comment by FluffyBunniesTasteTheBest** [comment]
@alnitak, @dumabg, Setting the deployment target to 13 fixes the build. Thanks for your help!

**Comment by alnitak** [comment]
> Flutter app uses Impeller, that needs a GPU support. In a hackintosh doesn't run because hasn't GPU support.
Thanks @dumabg, but even with Impeller disabled, the problem is that Flutter doesn't support OpenGL anymore and my hackintosh doesn't support Metal which is mandatory now to run apps on iOS or MacOS.

Thank you both @dumabg  and @FluffyBunniesTasteTheBest! I will update the plugin soon to fix this!

**Comment by dumabg** [comment]
In iOS simulator works. On Mac no.
I'm using docker-osx  https://github.com/sickcodes/Docker-OSX and can run an iOS app in the simulator with the last Flutter version.
