### ISSUE TITLE
Readme add a quick link to pub.dev

### ISSUE THREAD

**Issue by guyluz11** [alnitak/flutter_soloud#13]
It will be very convenient to have quick link to [pub.dev](https://pub.dev/packages/flutter_soloud) page of the package at the beginning of Readme file 

Currently 
![Screenshot_20230915_121934_Firefox](https://github.com/alnitak/flutter_soloud/assets/9304740/0e2c57ed-b839-4648-88fc-919a93091303)

Suggestion

![Screenshot_20230915_122015_Firefox](https://github.com/alnitak/flutter_soloud/assets/9304740/4d74cfb2-2b3d-4a8f-a09e-90b1124c3664)

**Comment by alnitak** [comment]
Done, thanks!

**Comment by alnitak** [comment]
fixed :D Thanks
