### ISSUE TITLE
fix: Issue with "unsupported option '-G' for target 'x86_64-apple-ios13.0-simulator'"

### ISSUE THREAD

**Issue by michcio53** [alnitak/flutter_soloud#130]
**Description**

**Steps To Reproduce**

1. Update xCode to 16.0 and macOS to 15
2. Use flutter_soloud with version 2.1.3
3. Try to compile iOS project from xcode or vs code on simulator (In my case iPhone 16 Pro)
4. Get error:
```
Error (Xcode): unsupported option '-G' for target 'x86_64-apple-ios13.0-simulator'

Error (Xcode): unsupported option '-G' for target 'arm64-apple-ios13.0-simulator'
```

**Expected Behavior**

App should compile without errors

**Screenshots**
Vscode:
![Screenshot 2024-09-18 at 13 30 15](https://github.com/user-attachments/assets/7dd827e9-bab1-4b4c-9508-bc9f8942aba7)

Xcode
![Screenshot 2024-09-18 at 13 30 53](https://github.com/user-attachments/assets/05826e40-72fb-43e9-a287-f668fdfd657d)

**Additional context**
When removing library from project, everything compiles fine

**Comment by alnitak** [comment]
Thanks @michcio53,

I think it's now fixed!
