### ISSUE TITLE
feat: mic input / capture

### ISSUE THREAD

**Issue by naychrist** [alnitak/flutter_soloud#132]
**Description**

This lib is great. However, I was disappointed to see that audio capture was removed. I was planning to use live audio input for a visualiser. My starting point was going to be to take the `audio_data` example and replace sound file input w microphone.

I understand why this was removed originally but is there any way to add this back as a separate package or recommendations on a third party package that would integrate well?

**Requirements**

- [ ] Capture live audio input, cross platform
- [ ] Extract data from the live input equivalent to the `audio_data` example

**Comment by alnitak** [comment]
Hi @naychrist,

I am writing a separate package with the same "philosophy" of flutter_soloud.
It will be able to listen and record with "silence detection and removal". It will also have a way to get wave and FFT data as flutter_soloud does, plus a volume dB value.

Actually, I just need to add web support and write docs since the release :(

**Comment by naychrist** [comment]
ah that sounds great @alnitak ! Any idea when you might release it? At the moment I would be content with desktop and an example to get me started.

**Comment by alnitak** [comment]
Hi @naychrist,

I have published a recorder plugin [here](https://github.com/alnitak/flutter_recorder).
It should work on all platforms web included, but I cannot test on mac/iOS.

So let's move there for any discussion!

**Comment by naychrist** [comment]
Amazing thank you! I can give it as spin and help test mac/ios after next week sometime.

**Comment by alnitak** [comment]
> How to integrate it with flutter_soloud and make live audio record with effects: echo, reverb,...?

I've just pushed a [PR to stream mic audio data](https://github.com/alnitak/flutter_recorder/pull/2). This data can be then passed to a new `AudioSource` in flutter_soloud and then use any filters you want.

This functionality will be available soon in flutter_soloud but you can try it now using the `websocket` branch. It is introduced [in this new PR](https://github.com/alnitak/flutter_soloud/pull/148).
