### ISSUE TITLE
fix: background noise when Pitch Shift filter is activated

### ISSUE THREAD

**Issue by mario-madrid** [alnitak/flutter_soloud#140]
**Description**

Hello. First, thank you for this amazing package. I have noticed when I use pitch shift filter, I can hear a little bit of background noise, even if we do nothing with the filter. 

**Steps To Reproduce**

With this code:

```
import 'dart:developer' as dev;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_soloud/flutter_soloud.dart';
import 'package:logging/logging.dart';

void main() async {
  // The `flutter_soloud` package logs everything
  // (from severe warnings to fine debug messages)
  // using the standard `package:logging`.
  // You can listen to the logs as shown below.
  Logger.root.level = kDebugMode ? Level.FINE : Level.INFO;
  Logger.root.onRecord.listen((record) {
    dev.log(
      record.message,
      time: record.time,
      level: record.level.value,
      name: record.loggerName,
      zone: record.zone,
      error: record.error,
      stackTrace: record.stackTrace,
    );
  });

  WidgetsFlutterBinding.ensureInitialized();

  /// Initialize the player.
  await SoLoud.instance.init();

  runApp(
    const MaterialApp(
      home: HelloFlutterSoLoud(),
    ),
  );
}

/// Simple usecase of flutter_soloud plugin
class HelloFlutterSoLoud extends StatefulWidget {
  const HelloFlutterSoLoud({super.key});

  @override
  State<HelloFlutterSoLoud> createState() => _HelloFlutterSoLoudState();
}

class _HelloFlutterSoLoudState extends State<HelloFlutterSoLoud> {
  AudioSource? currentSound;

  @override
  void dispose() {
    SoLoud.instance.deinit();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!SoLoud.instance.isInitialized) return const SizedBox.shrink();

    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            await SoLoud.instance.disposeAllSources();

            /// load the audio file
            currentSound = await SoLoud.instance
                .loadAsset('assets/audio/8_bit_mentality.mp3');

            // If I comment this line, the background noise disappear.
            SoLoud.instance.filters.pitchShiftFilter.activate();

            /// play it
            await SoLoud.instance.play(currentSound!);
          },
          child: const Text(
            'play asset',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
```

**Expected Behavior**

No background noise when I activate the pitch shift filter.

**Screenshots**

I attach two videos, one with the line commented (no noise) and other one with the filter activated (noise).

**Additional Context**

https://github.com/user-attachments/assets/348bd2e7-fcb9-4ff3-a9ee-ec728b4949ea

https://github.com/user-attachments/assets/a55ef5bb-198a-4909-8e7c-392b75216696

Tested on OPPO reno2 Z, physical device, either on release and debug mode.

**Comment by alnitak** [comment]
Hi @mario-madrid, thanks for the feedback.

This is probably caused because you are in debug mode. Could you please try in release mode?

**Comment by mario-madrid** [comment]
Hi @alnitak . I can confirm that is happening in release mode. I dont have another device to test, and it happens in the emulator too. :( could you reproduce it by yourself with the code I have posted please?

thank you in advance.

**Comment by alnitak** [comment]
Yes, I tried on these devices without noticing your issue:
Emulator with API 30
Samsung Galaxy Note S20
Samsung Galaxy S9+
Xiaomi Mi Max3
Huawei P Smart Z
Redmi Note 8 Pro

It seems like a problem related to computational power. 

Since I cannot try it on my devices, can you please do the following?
In the plugin folder modify the following line in `android/CMakeLists.txt`:

[target_compile_options("${PLUGIN_NAME}" PRIVATE -Wall -Wno-error -fPIC -O0)](https://github.com/alnitak/flutter_soloud/blob/f32e5eedc0d8f057bd36824fa4214410443ed5cd/android/CMakeLists.txt#L68)

with this:

```
target_compile_options("${PLUGIN_NAME}" PRIVATE -Wall -Wno-error -fPIC -O0 -msse3 -msse2)
```

Then run a `flutter clean` and try again.

**Comment by mario-madrid** [comment]
It can be a computational power issue. The phone is really old. I will try what are you suggesting a provide some feedback.

I’m happier if, with more modern devices, the issue is not happening.

Give me a few data to test your code.

Thank you!

**Comment by mario-madrid** [comment]
Hello mate. 

It's looks like something random, sometimes happens and sometimes does not happen. Will see in another real devices since in the emulator, with all the stuff that the computer has to do, I don't think is a good scenario for test.

Anyways, my use case is to play multiple voices at the same time. Now i'm playing 7 mp3 audio files of 3 minutes each, is for a choir app. I think is hard to listen what I'm talking about, but will see with my client.

Dunno if you want to investigate something more about it or if you want me to close the issue.

Thank you for all the help.

**Comment by alnitak** [comment]
My thought is that pitchShift might be quite cpu intensive, if you use it as a global filter (`SoLoud.instance.pitchShift`) there will only be one active filter on the output, but if you use it on 7 different sounds (with `AudioSource.filter.pitchShift`), there will be 7 active computations.

**Comment by mario-madrid** [comment]
Yes. Ive tried activating filter on each sound and is unaudible. Luckily, global filter is enough for my use case but I still notice that little noise. Maybe with newer device and some optimizations I can reach Perfect sound. I want to try to change audio format from mp3 to AAC and use disk load mode.

will report whatever improvement i achieve.

One question. Is there any chance to play audio in chunks downloaded from internet?

thanks!

**Comment by alnitak** [comment]
> I want to try to change audio format from mp3 to AAC and use disk load mode.

I think AAC is not supported by the plugin.

> One question. Is there any chance to play audio in chunks downloaded from internet?

I am working on that! I got good results sending data received from a websocket of PCM audio! I'll soon open an issue explaining this new feature!

**Comment by mario-madrid** [comment]
Ok. Will see that feature.

for the issue, I’ve improved the logic of the application and tried a new device and now it’s working.

i close the issue if you don’t mind.
