### ISSUE TITLE
fix: SoLoud.instance.loadAsset future does not fail when an error loading the file occurs.

### ISSUE THREAD

**Issue by joshuagore-aofl** [alnitak/flutter_soloud#145]
**Description**

If you call SoLoud.instance.loadAsset (or any other load that returns an audio source) in a way that will break (For example by trying to play a corrupted audio file), the future does not fail as I would expect it to.

**Steps To Reproduce**

1. Take a png and rename it to mp3.
2. Attempt loading this file using SoLoud.instance.loadAsset('fakeAudioFile.mp3')
3. See that we do get logs of the error occuring but the future is not failed

**Expected Behavior**

Within soloud.dart, immediately before `throw SoLoudCppException.fromPlayerError(error);` is called within the listener on `_controller.soLoudFFI.fileLoadedEvents.listen` we should probably add 
`loadedFileCompleters[result['completeFileName']]?.completeError(SoLoudCppException.fromPlayerError(error),);`

**Screenshots**

![suggested resolution](https://github.com/user-attachments/assets/82c7946e-6ba4-455b-a8a5-d82076da9523)

**Comment by alnitak** [comment]
Thank you very much. Good catch!

Updating to v2.1.7
