### ISSUE TITLE
docs: Audio comming from earpiece speaker

### ISSUE THREAD

**Issue by AdnanKhaleeli** [alnitak/flutter_soloud#159]
**Description**

So I am making a Metronome Application that uses continuous listening for user input, along with audio output. There seems to be an issue with soLoud on an actually device goes to the earpiece speaker. Is there a way to fix this. I noticed this happens when the speech recognition isn't on. So its's a resource issue between my input and output. I do not know if I just missed it, I did see something called PlayBackDevice, but I was not too confident if it would change it.

**Requirements**

- [ ] Requirements go here

**Comment by alnitak** [comment]
Hi @AdnanKhaleeli,

the output device used by the plugin is the default one that the OS uses. If the OS switches it, I think, also the plugin will use it.

You can set which device the plugin should use by taking the [list of available devices](https://github.com/alnitak/flutter_soloud/blob/5303435ce7ce5a3fdba6b564e62a81c953bd9e49/example/lib/output_device/output_device.dart#L79) and then [setting your desired one](https://github.com/alnitak/flutter_soloud/blob/5303435ce7ce5a3fdba6b564e62a81c953bd9e49/example/lib/output_device/output_device.dart#L104).

The example in the link above shows how to do this. I never tried to set a fixed output device and see if it still when the OS changes it. Please, let me know if it works.

**Comment by alnitak** [comment]
@AdnanKhaleeli I searched for this problem around. It seems that some applications like Messenger, Tik Tok, or whatever apps that let you record and listen, lock the output to the ear speaker in some unknown circumstances. You should find which app causes this and force-stop it or try to restart your phone.
That's all I have found.

**Comment by AdnanKhaleeli** [comment]
I

**Comment by AdnanKhaleeli** [comment]
So I simply changed the order and it worked. I don't actually have an IOS device, so I had to wait a while before I could test it on my fellow classmates. Idk if he had another application on the RAM the first time, or if I changed something else within the code. I think the initialization order takes the best speaker first. However, that is my unconfirmed theory
