### ISSUE TITLE
fix: Slow soLoud.loadMem(uri, buffer!)

### ISSUE THREAD

**Issue by te8uekm12** [alnitak/flutter_soloud#162]
**Description**
Hi, 
In my case fast and on time playing of short audio is crucial.
I found that soLoud.loadMem takse about 500miliseconds (each time) for buffer of an mp3 file with size is 35390. Is it possible to speed it up or make advantage of cache during creation?

Long building time of an AudioSource

**Steps To Reproduce**

Future<EAudioPlayerStatus> playAsync(String uri, GAudioProperties properties) async {
    int start = GTimeUtils.currentTimeInMillis();
   
    final Uint8List? buffer = await zz.byteFile.readAsync(uri);
    logger.logInfo('@-> playAsync 1', () => '$uri load from file -> ${GTimeUtils.currentTimeInMillis() - start} millis, bufferSize: ${buffer!.length}');

    start = GTimeUtils.currentTimeInMillis();
    final AudioSource audioSource = await soLoud.loadMem(uri, buffer!);
    logger.logInfo('@-> playAsync 2', () => '$uri build AudioSource -> ${GTimeUtils.currentTimeInMillis() - start} millis');
    start = GTimeUtils.currentTimeInMillis();
    
    await soLoud.play(audioSource);

    logger.logInfo('@-> playAsync 3', () => '$uri played -> ${GTimeUtils.currentTimeInMillis() - start} millis');
    return EAudioPlayerStatus.ok;
  }

Log below:

[INFO] >> GLogService::@-> playAsync 1 >> /resources/sounds/whip2.mp3 load from file -> 29 millis, bufferSize: 35390
[INFO] >> GLogService::@-> playAsync 2 >> /resources/sounds/whip2.mp3 build AudioSource -> 480 millis
[INFO] >> GLogService::@-> playAsync 3 >> /resources/sounds/whip2.mp3 played in -> 0 millis

**Expected Behavior**

For second call to await soLoud.loadMem(uri, buffer!); it should quick return cached value.

**Screenshots**

**Additional Context**

**Comment by alnitak** [comment]
this is an unavoidable consequence when reading a file. With `load*` methods, the audio is read and decoded into memory for later use.

You have two options:
1. use `loadMem` or `loadFile` to get the `AudioSource` (maybe when you initialize the app), use it when you want to play it. It should be almost instantaneous.
2. use `loadFile(uri, mode: LoadMode.disk)` which will not read the whole file and decode it to memory, but it will play I think faster than you did in your code.

Let me know!

**Comment by te8uekm12** [comment]
Hi, thanks for explanation it helped :) cache solved the problem.
