### ISSUE TITLE
docs: Capture

### ISSUE THREAD

**Issue by themailman05** [alnitak/flutter_soloud#17]
**Description**
Thank you for your hard work on this awesome project.

I would like to create some documentation for how to use the capture interface to get raw WAV audio.
I see the miniaudio callback function in `capture.cpp` copies the wav data to a float buffer of length 1024.
I would like to access that raw capture data and pass in my own `data_callback` to handle the data, if something like this does not already exist.
I believe the getCaptureAudioTexture2d function is the only interface exposed currently that allows something like this.
It's not clear to me how to use it for a case other than visualization as the ticker in the demo project seems to be synchronized to screen render rather than new data available from the capture device.

I think a C++ extension ability to overload that callback method or some other way to add logic in that callback would really help.

I can contribute code and documentation if you can help me understand how this might be possible.

Thank you.

**Comment by alnitak** [comment]
Hi @themailman05,

I reviewed the code a bit because it's been a while since i wrote that. 
You are right, the `getCaptureAudioTexture2d` is the only function exposed here. It takes the first 256 floats of the captured buffer samples and use them to calculate the FFT returning one 2D array where each row (512 floats) is represented by 256 floats of FFT data and 256 float with wave data. 
So you can use just the 2nd 256 floats of the first row (which is the latest data). But as said before, the buffer is 1024. You will lose the other 768 floats.

It was planned to add a function to get all the buffer, but some testing are needed. 
The way to proceed:
1. the miniaudio callback fills and replaces data of the buffer every time is called
2. the miniaudio callback must not do anything expensive
3. write a C function to get the buffer and its Dart binding

The problem:
from Dart, after calling the get buffer method, you are supposed to do something with that data. Meanwhile the miniaudio callback might have been called many times and so you will lose those new buffer data.
I don't know how to solve this if it is a real problem, losing some data from the mic could't be a problem in most cases. My thoughts is to write a temp file or a buffer that decrease when requesting data (and increases when the miniaudio callback is called).

If you want to contribute in some way that would be great!! I'm terrible at writing docs, some guys told me they were scared reading it! :)

Anyway, In this week end I'll try to do something. Let me know.

Thanks

**Comment by themailman05** [comment]
Hey Marco,I’m going to hop online and try some of your suggestions today to see if I can get it working. I would like to use a temporary ring buffer with a toggle to write the stream to disk or straight into a player buffer.LiamOn Nov 18, 2023, at 10:16 AM, Marco Bavagnoli ***@***.***> wrote:﻿
Hi @themailman05,
I reviewed the code a bit because it's been a while since i wrote that.
You are right, the getCaptureAudioTexture2d is the only function exposed here. It takes the first 256 floats of the captured buffer samples and use them to calculate the FFT returning one 2D array where each row (512 floats) is represented by 256 floats of FFT data and 256 float with wave data.
So you can use just the 2nd 256 floats of the first row (which is the latest data). But as said before, the buffer is 1024. You will lose the other 768 floats.
It was planned to add a function to get all the buffer, but some testing are needed.
The way to proceed:

the miniaudio callback fills and replaces data of the buffer every time is called
the miniaudio callback must not do anything expensive
write a C function to get the buffer and its Dart binding

The problem:
from Dart, after calling the get buffer method, you are supposed to do something with that data. Meanwhile the miniaudio callback might have been called many times and so you will lose those new buffer data.
I don't know how to solve this if it is a real problem, losing some data from the mic could't be a problem in most cases. My thoughts is to write a temp file or a buffer that decrease when requesting data (and increases when the miniaudio callback is called).
If you want to contribute in some way that would be great!! I'm terrible at writing docs, some guys told me they were scared reading it! :)
Anyway, In this week end I'll try to do something. Let me know.
Thanks

**Comment by themailman05** [comment]
Tinkering with it a bit this weekend. I tried just refactoring the getAudioTexture2D but without `printf` statements showing up I am having a hard time debugging the C++ side. Any tips for getting debug printing to display? Would help a great deal.

**Comment by alnitak** [comment]
On Android the printf doesn't output on console as you noticed. It has its own log like `__android_log_vprint()`. I have written a common `platform_log()` in [common.h](https://github.com/alnitak/flutter_soloud/blob/07b86999ecda21379ac07773d6521d5497b60da6/src/common.h#L53) which should work but I didn't tested well on other platforms.

If you are using VS Code you could also debug C/C++ code. I set up the run actions in `.vscode/launch.json` for linux and windows, but you should install `C/C++ Extension Pack` and `C/C++ for Visual Studio Code` by Microsoft. 
To debug C/C++ code with Android Studio, you should open the `android` folder project and edit the run configuration to use native debug.

**Comment by alnitak** [comment]
Some times ago I did already a circular buffer class. Feel free to use it

<details>
<summary>circular_buffer.h</summary>

```
#ifndef CIRCULAR_BUFFER_H
#define CIRCULAR_BUFFER_H

#include <iostream>
#include <vector>
#include <algorithm>

class CircularBuffer {
private:
    std::vector<float> buffer;
    size_t maxSize;
    size_t currentSize;
    size_t head;
    size_t tail;

public:
    explicit CircularBuffer(size_t size) : buffer(size), maxSize(size), currentSize(0), head(0), tail(0) {}

    int size() {return currentSize;}

    void push(const std::vector<float>& values) {
        size_t numValues = values.size();

        // Check if the buffer is full
        if (currentSize + numValues > maxSize) {
            size_t numToRemove = currentSize + numValues - maxSize;
            head = (head + numToRemove) % maxSize;
            currentSize -= numToRemove;
        }

        size_t numTail = std::min(numValues, maxSize - tail);

        // Copy values to the tail of the buffer
        std::copy(values.begin(), values.begin() + numTail, buffer.begin() + tail);

        // If there are remaining values, copy them to the head of the buffer
        if (numValues > numTail) {
            std::copy(values.begin() + numTail, values.end(), buffer.begin());
        }

        tail = (tail + numValues) % maxSize;
        currentSize = std::min(currentSize + numValues, maxSize);
    }

    std::vector<float> pop(size_t numValues) {
        numValues = std::min(numValues, currentSize);
        std::vector<float> poppedValues(numValues);

        size_t numTail = std::min(numValues, maxSize - head);

        // Copy values from the head of the buffer
        std::copy(buffer.begin() + head, buffer.begin() + head + numTail, poppedValues.begin());

        // If there are remaining values, copy them from the tail of the buffer
        if (numValues > numTail) {
            std::copy(buffer.begin(), buffer.begin() + numValues - numTail, poppedValues.begin() + numTail);
        }

        head = (head + numValues) % maxSize;
        currentSize -= numValues;

        return poppedValues;
    }

    void print() const {
        std::cout << "N: " << currentSize << " - ";
        for (size_t i = 0; i < currentSize; ++i) {
            size_t index = (head + i) % maxSize;
            std::cout << buffer[index] << " ";
        }
        std::cout << std::endl;
    }
};



#endif // CIRCULAR_BUFFER_H
```

</details>

**Comment by themailman05** [comment]
Hello,

I have made some progress on audio capture to buffer, but having some trouble with formats.
As I understand it the `void* pInput` incoming to `data_callback` is an interleaved 2-channel float32 buffer.

I am using memcpy in the callback to write to a preallocated buffer.

I am now working on exposing the [SoLoud Wav loadMem](https://solhsa.com/soloud/wav.html) bindings as function calls as well.

I think actually I need to use SoLoud Wav loadRawWave for the float pcm buffer that is emitted from the capture callback. I am still learning miniaudio so please let me know if I am on the right track. I'm happy to contribute back what I build once I get the kinks worked out.
