### ISSUE TITLE
feat: I want to change the color from red to white.

### ISSUE THREAD

**Issue by younasud** [alnitak/flutter_soloud#18]
Could you please help me change the color from red to white?

<img width="378" alt="Screenshot 2023-11-23 at 6 17 10 PM" src="https://github.com/alnitak/flutter_soloud/assets/33557291/10d43a67-686d-4520-81af-61a3c1e10e24">

**Comment by younasud** [comment]
> That's is an image created using [SoLoud().getAudioTexture2D()](https://github.com/alnitak/flutter_soloud/blob/07b86999ecda21379ac07773d6521d5497b60da6/lib/src/soloud.dart#L858C4-L858C4) which returns the last 256 row of samples. The image is created [here](https://github.com/alnitak/flutter_soloud/blob/07b86999ecda21379ac07773d6521d5497b60da6/example/lib/visualizer/visualizer.dart#L418C16-L418C16) where `bytes` list is filled with RGBA values

Thank You  for quick response  @alnitak, but I'm trying and not getting any successful results. Can you help me change the color and share the code with me?

**Comment by alnitak** [comment]
the `bytes` within the code I linked, represents RGBA values. So if you change it to have the same value, you'll get a gray scaled image:
```
        final value = textureTypeCallback(y, x);
        bytes[y * fftBitmapRange * 4 + col * 4 + 0] = value;
        bytes[y * fftBitmapRange * 4 + col * 4 + 1] = value;
        bytes[y * fftBitmapRange * 4 + col * 4 + 2] = value;
        bytes[y * fftBitmapRange * 4 + col * 4 + 3] = 255;
```

**Comment by younasud** [comment]
> final value = textureTypeCallback(y, x);
>         bytes[y * fftBitmapRange * 4 + col * 4 + 0] = value;
>         bytes[y * fftBitmapRange * 4 + col * 4 + 1] = value;
>         bytes[y * fftBitmapRange * 4 + col * 4 + 2] = value;
>         bytes[y * fftBitmapRange * 4 + col * 4 + 3] = 255;

Just wanted to say a huge thank you for your invaluable help. Your support meant a lot. Truly appreciate it!

**Comment by younasud** [comment]
Hi @alnitak, Can you help me? I want to clear the above shader when I start capturing again. At this time, when I begin capturing anew, it should also display the data from the last capture
