### ISSUE TITLE
Load audio from url

### ISSUE THREAD

**Issue by zhusupq** [alnitak/flutter_soloud#2]

**Comment by alnitak** [comment]
Unfortunately the SoLoud lib doesn't have this feature available.
I close this for now, but soon or later I will try to find a way to implement this.

**Comment by alnitak** [comment]
I reopen this. In issue #4 we discuss to add some tools with play from url included.
Regarding my previous comment, it will imply that the audio must be downloaded before playing it, no streaming feature will be possible for now.

**Comment by alnitak** [comment]
the new [PR](https://github.com/alnitak/flutter_soloud/pull/5) adds also this enhancement.
You can now do
```
SoundProps? s = SoloudLoadingTool.loadFromUrl(
      'https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3',
);
```
to load a network sound
