### ISSUE TITLE
How I can change opacity of the red lines and set pitch

### ISSUE THREAD

**Issue by Hassan763** [alnitak/flutter_soloud#22]
Can you please guide me how to give the opacity to the sound wave (the red lines)

<img width="378" alt="285218770-10d43a67-686d-4520-81af-61a3c1e10e24" src="https://github.com/alnitak/flutter_soloud/assets/61411612/b0872fcc-34c9-465e-8571-bc2c6aa06650">

I also need  to set the Pitch of the audio while capturing and playing.

**Comment by alnitak** [comment]
> Can you please guide me how to give the opacity to the sound wave (the red lines)

Please see #18

> I also need to set the Pitch of the audio while capturing and playing.

There is not yet this feature

**Comment by Hassan763** [comment]
I have seen the issue you have quote but that wast to change the color I have tried that but unable to change the opacity

**Comment by alnitak** [comment]
> I have seen the issue you have quote but that wast to change the color I have tried that but unable to change the opacity

That issue points to an example that visualize FFT data as RGBA colors. So Red, Green, Blue and Alpha channel. The latter is the opacity.
You can use the FFT data as you wish to compose visualizations, but this is out of scope of this plugin.
