### ISSUE TITLE
fix: Building project using Linux it does not build the app

### ISSUE THREAD

**Issue by JUANITOTELO** [alnitak/flutter_soloud#23]
**Description**

When building a project importing the library it doesn't build the app so it can't be executed or even debuged :(

**Steps To Reproduce**

1. Create a project using Ubuntu
2. Import the _flutter_soloud_ library
3. Run the project
4. here it is my log

Launching lib/main.dart on SM P613 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_soloud:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/android/.cxx/Debug/333x3t5f/arm64-v8a'
  [1/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/common.cpp.o
  [2/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/synth/basic_wave.cpp.o
  [3/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/analyzer.cpp.o
  [4/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_audiosource.cpp.o
  [5/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_bus.cpp.o
  [6/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_3d.cpp.o
  [7/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_basicops.cpp.o
  [8/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_filterops.cpp.o
  [9/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_faderops.cpp.o
  [10/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud.cpp.o
  [11/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_getters.cpp.o
  [12/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_voicegroup.cpp.o
  [13/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_fader.cpp.o
  [14/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp.o
  FAILED: CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp.o
  /home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DFLUTTER_PLUGIN_IMPL -DWITH_MINIAUDIO -DWITH_NULL -Dflutter_soloud_plugin_EXPORTS -I../../../../../src/soloud/include -I../../../../../src/soloud/src -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -fvisibility=hidden -Wall -Wno-error -fPIC -std=gnu++14 -MD -MT CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp.o -MF CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp.o.d -o CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp.o -c /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp:1:
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.h:10:
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.h:21:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp:646:57: warning: result of comparison of constant -1 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
          if (player.mFilters.addGlobalFilter(filterType) == -1)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
  /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings.cpp:660:60: warning: result of comparison of constant -1 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
          if (player.mFilters.removeGlobalFilter(filterType) == -1)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
  2 warnings and 1 error generated.
  [15/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_setters.cpp.o
  [16/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_fft_lut.cpp.o
  [17/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_core_voiceops.cpp.o
  [18/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp.o
  FAILED: CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp.o
  /home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DFLUTTER_PLUGIN_IMPL -DWITH_MINIAUDIO -DWITH_NULL -Dflutter_soloud_plugin_EXPORTS -I../../../../../src/soloud/include -I../../../../../src/soloud/src -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -fvisibility=hidden -Wall -Wno-error -fPIC -std=gnu++14 -MD -MT CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp.o -MF CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp.o.d -o CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp.o -c /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/bindings_capture.cpp:11:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [19/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/capture.cpp.o
  [20/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_file.cpp.o
  [21/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp.o
  FAILED: CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp.o
  /home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DFLUTTER_PLUGIN_IMPL -DWITH_MINIAUDIO -DWITH_NULL -Dflutter_soloud_plugin_EXPORTS -I../../../../../src/soloud/include -I../../../../../src/soloud/src -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -fvisibility=hidden -Wall -Wno-error -fPIC -std=gnu++14 -MD -MT CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp.o -MF CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp.o.d -o CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp.o -c /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.cpp:1:
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.h:21:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [22/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/soloud/src/core/soloud_fft.cpp.o
  [23/63] Building CXX object CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp.o
  FAILED: CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp.o
  /home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/hto/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DFLUTTER_PLUGIN_IMPL -DWITH_MINIAUDIO -DWITH_NULL -Dflutter_soloud_plugin_EXPORTS -I../../../../../src/soloud/include -I../../../../../src/soloud/src -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -fvisibility=hidden -Wall -Wno-error -fPIC -std=gnu++14 -MD -MT CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp.o -MF CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp.o.d -o CMakeFiles/flutter_soloud_plugin.dir/home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp.o -c /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp:2:
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.h:10:
  In file included from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/filters/filters.h:21:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/src/player.cpp:135:57: warning: implicit conversion from 'long long' to 'unsigned int' changes value from 9223372036854775807 to 4294967295 [-Wconstant-conversion]
      std::uniform_int_distribution<unsigned int> dist(0, INT64_MAX);
                                                  ~~~~    ^~~~~~~~~
  /snap/flutter/current/usr/include/stdint.h:124:22: note: expanded from macro 'INT64_MAX'
  # define INT64_MAX              (__INT64_C(9223372036854775807))
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /snap/flutter/current/usr/include/stdint.h:109:24: note: expanded from macro '__INT64_C'
  #  define __INT64_C(c)  c ## LL
                          ^~~~~~~
  <scratch space>:348:1: note: expanded from here
  9223372036854775807LL
  ^~~~~~~~~~~~~~~~~~~~~
  1 warning and 1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /home/hto/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/android/.cxx/Debug/333x3t5f/arm64-v8a \
        flutter_soloud_plugin
    from /home/hto/.pub-cache/hosted/pub.dev/flutter_soloud-1.2.4/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1


Exited (1).



**Expected Behavior**

Run the app in the android device connected to the computer.

**Additional Context**

I ask and maybe it's the NDK, I don't know what that is actually...

**Comment by alnitak** [comment]
Hi,
in the log, I see you used `snap` to install Flutter. Searching for the error in the log I have found that installation  with `snap` could be [the problem](https://stackoverflow.com/questions/70149507/flutter-build-failed-for-android-bitmapexternalnativebuilddebug) which I found from [here](https://stackoverflow.com/questions/74930890/execution-failed-for-task-rive-commonbuildcmakedebugarm64-v8a)

This is your compilation error you should look at:
`memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information`

Let me know if you find something!

**Comment by JUANITOTELO** [comment]
> Hi, in the log, I see you used `snap` to install Flutter. Searching for the error in the log I have found that installation with `snap` could be [the problem](https://stackoverflow.com/questions/70149507/flutter-build-failed-for-android-bitmapexternalnativebuilddebug) which I found from [here](https://stackoverflow.com/questions/74930890/execution-failed-for-task-rive-commonbuildcmakedebugarm64-v8a)
> 
> This is your compilation error you should look at: `memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information`
> 
> Let me know if you find something!

Thanks! That was it! What a weird bug...
