### ISSUE TITLE
Cannot find how to play recorded sound

### ISSUE THREAD

**Issue by dorklord23** [alnitak/flutter_soloud#25]
**Description**

Even after reading the docs for a few hours. I can't find how to play recorded sound from microphone. There is no mention about how to play such recording in the docs.

Best I can find is this following excerpt: `With the audio data it will be simple to do something like in the 1st example:` but it's far from helpful.

**Comment by dorklord23** [comment]
Your work is much appreciated nonetheless :)

Which part of the 1st example visualizing the audio data? I still can't find it :(

**Comment by alnitak** [comment]
I meant the circle you can see in the video [here](https://github.com/alnitak/flutter_soloud#capture-from-microphone)

The code to build that circle widget is located in [page_hello_flutter.dart](https://github.com/alnitak/flutter_soloud/blob/07b86999ecda21379ac07773d6521d5497b60da6/example/lib/page_hello_flutter.dart#L69)
