### ISSUE TITLE
docs: How to get getAudioTexture in specific time?

### ISSUE THREAD

**Issue by BigGitWorld** [alnitak/flutter_soloud#27]
Hello.
Please suppose I have a wav file with duration of 6 seconds. 
1.
I want to get frequencies and wave data at a specific time (for example 2.5 second after start). in fact I want to find maximum amplitude and its frequency at a specific time.
2.
I want to get frequencies and wave for a time duration (for example between 2.5 and 3.5 seconds).

How can I do it?

**Comment by alnitak** [comment]
Hi @BigGitWorld,

thank you for pointing me to this.
For now, the plugin is not yet ready to do this. At least not correctly if you want to use `getAudioTexture2D`, since it grabs the current data that may not returned sequentially at every call.

I plan to implement something useful for this, but I don't know when I will.

**Comment by BigGitWorld** [comment]
Hi @alnitak 
Thanks for your answer.
But something is not clear to me.
In your [visualizer example](https://github.com/alnitak/flutter_soloud/blob/fe0cb2babfcacd11ceaa265cbc0877f7e07fd534/example/lib/visualizer/visualizer.dart#L98) , you have used:
```
//these constants must not be touched since SoLoud gives back a size of 256 values
fftSize = 512;
halfFftSize = fftSize >> 1;
```
but in issue [20](https://github.com/alnitak/flutter_soloud/issues/20), you told me:
```
Since the engine is set to 44100 samples/s and the amount of data given to compute FFT is 1024, below a function to know which frequency is represented in the array index i.
```
So, what value is used for ``n_fft`` to calculate frequency (Hz) from index?
