### ISSUE TITLE
How to get onsets and pitches?

### ISSUE THREAD

**Issue by BigGitWorld** [alnitak/flutter_soloud#28]
Hello dear @alnitak 
How to get onsets and pitches?

**Comment by alnitak** [comment]
I think I didn't understand your question.
If your goal is to perform some analysis on audio data, this plugin is not meant to do that. Maybe these features will be added later (indeed almost certainly!!), but not soon I think.

**Comment by synchronisator** [comment]
Only for information:
I use https://pub.dev/packages/pitch_detector_dart for pitch detection but until now with flutter_audio_capture instead of SoLoud, because i just migrated my output to SoLoud but not the input

**Comment by alnitak** [comment]
I think you can still use *pitch_detector_dart* for that. It accepts a `List<double> so you have to take those values from your call to [getAudioTexture2D](https://github.com/alnitak/flutter_soloud/blob/fe0cb2babfcacd11ceaa265cbc0877f7e07fd534/lib/src/soloud.dart#L858)
