### ISSUE TITLE
feat: Find a better mechanism than the `audioEvent` stream for listening to changes in the engine

### ISSUE THREAD

**Issue by filiph** [alnitak/flutter_soloud#36]
**Description**

From https://github.com/alnitak/flutter_soloud/issues/31#issuecomment-1985672770:

> Find a better way to expose `SoLoud().audioEvent` stream. Now it is set as a [broadcast](https://github.com/alnitak/flutter_soloud/blob/1a9764c27c8dc7497471e9fa0b4bf600da2adfa3/lib/src/soloud.dart#L89) inside a singleton class. Is it worth considering moving the event stream flow to a dedicated class? Now the developer can subscribe to it (like I did wrongly) and then he needs to remove that subscription, which is not possible IIRC with a broadcast.

One relatively simple solution ("A") would be to use `ValueNotifier` or `ChangeNotifier` or `Listenable`. These are synchronous and don't have the issues that broadcast streams have. There's less language support for those, though. The code would look like this:

```dart
final soloud = SoLoud();

soloud.captureRunning.addListener(_handleCaptureChange);

...

soloud.captureRunning.removeListener(_handleCaptureChange);
```

Another (half-) solution ("B") is already in the API changes propsals: `"Expose a Future<void> or Future<bool> that notifies when SoLoud is initialized"`. This would make it easier to await engine initialization, and so `audioEvent` would not be needed for the vast majority of use cases.

```dart
    final soloud = SoLoud();
    await soloud.initialize();
    
    // Elsewhere:
    await soloud.ready;
    ... do stuff ...
```

Yet another solution ("C") would be to allow registering callbacks upon SoLoud construction. This solution is closely related to https://github.com/alnitak/flutter_soloud/issues/35. Something like:

```dart
final engine = SoLoud(
  onCaptureStarted: () {
    ...
  },
);
```

And the last solution ("D") that comes to mind is to change `audioEvents` to a normal (single-subscriber, non-broadcast) stream. These are much easier to reason about, and throw when more than one subscriber wants to subscribe. Normal streams also automatically close when the (single) subscriber stops listening, and they "keep" all events (you can't miss any event).

This option could either have the same or similar API (except there would be a big warning that only one subscriber can subscribe), or it could be something similar as option "C", where only the caller of the constructor or the `initialize()` method can get a hold of the stream.

```dart
    final soloud = SoLoud();
    try {
      final result = await soloud.initialize();
      _lifecycleSubscription = result.lifecycleStream.listen(_handleLifecycleEvent);
    } on SoLoudInitializationError catch (e) {
      // ...
    }

    ...

    // In dispose.
    _lifecycleSubscription.cancel();
```

My current position is to start with option "B". Let people listen to all audio engine events if they want to, but remove the most important reason by making it much easier to just check whether the engine is ready.

**Comment by filiph** [comment]
I also just realized that `audioEvents`, when split between `SoLoud` player and `SoLoud` capture, is just a way to asynchronously wait for a) the end of `initialize()` and b) the end of `dispose()`. I think it's clearer to remove `audioEvents` entirely (after a deprecation period, of course), and just have something like this:

```dart
soloud.onInitialized.listen(...);
soloudCapture.onDisposed.listen(...);
```

or even something much cruder:

```dart
// Only allows a single listener.
soloud.onInitialized = () { ... };
```

What's complicating this is that SoLoud cannot be instanced (https://github.com/alnitak/flutter_soloud/issues/35). Otherwise, we could assume that every instance of SoLoud is both initialized and disposed _at most once_. If that was the case, we probably wouldn't need `audioEvent` at all. You'd just `await soloud.initialize()` and `await soloud.dispose()` and you're done.

**Comment by alnitak** [comment]
By making changes and tests with the example code, I think we should consider having a listener not bound to the SoLoud instance, but a listener that can be listened everywhere in the code like a state manager.

I had some considerations, maybe some are not really related to this issue but maybe they will be managed better in the future based on the decision we will take with this issue:
- all the functionalities like `loadFile()`, `setWaveformFreq()`, and some others,  need the engine to be started and the developer must know the availability of the engine. These methods can be called everywhere in the code.
- an error or a state change to the player could occur and maybe it stops (a call on mobile is coming, the user turned the app in the background to watch a YouTube video). The developer should be notified of this.
- the `SoLoud().dispose()` is a `Future<bool>` and the `SoLoud().initialize()` is a `Future<PlayerErrors>`. So we cannot call `initialize()` before the `dispose()` is ended, but if we do (and this maybe could happen with something like `soloud.onInitialized.listen(...)`), we will get an error.
- in the example, we have the `Controls()' buttons that change color when the player changes state, and elsewhere we should know when the player is initialized to load sounds.

I am pro to your solution ("A") and solution ("B") both implemented. Could it be a good idea? We could just do "B" and see how the plugin evolves to add other solutions. I will stand with your decision and experience!
