### ISSUE TITLE
feat: Implement setProtectVoice()

### ISSUE THREAD

**Issue by filiph** [alnitak/flutter_soloud#53]
**Description**

Up till now, I didn't realize that, in case there are more voices than available channels, the oldest playing sound will be stopped by SoLoud. 

This could be a big problem in games, where the oldest playing sound is the background music, and where there are many sounds being played over each other all the time. It's easy to imagine that the player comes into a busy area, and suddenly music stops and never returns.

SoLoud's solution is [Soloud.getProtectVoice(), Soloud.setProtectVoice()](https://solhsa.com/soloud/attributes.html).

**Requirements**

- [ ] Introduce `bool getProtectVoice(SoundHandle h)` to `SoLoud`
- [ ] Introduce `void setProtectVoice(SoundHandle h, bool value)` to `SoLoud`

**Comment by alnitak** [comment]
I completely forgot about that! By default, the maximum number of handles (or voices) is set to 16. This value can be raised, but performances will be affected. I didn't understand if only when playing tens of sounds, that would be obvious, or just raising that limit. 

The solution is to use the functions you mentioned or raise that default value with [`setMaxActiveVoiceCount()`](https://solhsa.com/soloud/voicemanagement.html).

I read somewhere in the docs that is not a good idea to set all voices as `protected`, but it's a good idea set as protected for example a background game music. For sure is a good idea to expose all these functions to the plugin! I'll do it soon.
