### ISSUE TITLE
flutter_localizations  version conflict

### ISSUE THREAD

**Issue by lchshadow** [alnitak/flutter_soloud#6]
Error msg:

Because no versions of flutter_soloud match >1.1.1 <2.0.0 and flutter_soloud 1.1.1 depends on intl ^0.18.1, flutter_soloud ^1.1.1 requires intl ^0.18.1.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_soloud ^1.1.1 is incompatible with flutter_localizations from sdk.
So, because audio depends on both flutter_localizations from sdk and flutter_soloud ^1.1.1, version solving failed.

**Comment by alnitak** [comment]
I have removed intl dependency. You should not see that compile error now
