### ISSUE TITLE
feat: Simplified Recording Mechanism

### ISSUE THREAD

**Issue by synchronisator** [alnitak/flutter_soloud#74]
**Description**

I try to record the input from the Microphone and pass it to a library to detect the pitch. ( https://github.com/techpotatoes/pitch_detector_dart`)
And to be honest. i am not able to do it. Its only a `Pointer: address=0x7fa925708ce0`
I am not able to get the values out of a `ffi.Pointer<ffi.Pointer<ffi.Float>>` and i have no idea what to do or even if its recording or not. Maybe i am doing something wrong in the initialization or something...
It would be great to have a method where i can recieve a list like:
`[-0.012298583984375, -0.011810302734375, -0.011444091796875, -0.010650634765625, -0.011383056640625, ....`

Maybe some kind of
```
    SoLoudCapture.instance.startCapture(
        listener: (List<double> values) => print(values),
        onError: (e) => print(e),
    );
```

Thanks

**Comment by synchronisator** [comment]
Yes, i saw that. But i cant access any kind of value in my example.
What i do is mainly this:
```dart
  late ffi.Pointer<ffi.Pointer<ffi.Float>> audioData;

  @override
  void initState() {
    audioData = calloc();
    super.initState();
  }

  @override
  void dispose() {
    SoLoudCapture.instance.stopCapture();
    _timer?.cancel();
    calloc.free(audioData);
    super.dispose();
  }

  void startRecording() async {
    print("startRecording");
    if(!SoLoudCapture.instance.isCaptureInited){
      print("init");
      print(SoLoudCapture.instance.listCaptureDevices());
      final CaptureErrors a = SoLoudCapture.instance.initialize();
      final CaptureErrors b = SoLoudCapture.instance.startCapture();
      if (context.mounted &&
          a == CaptureErrors.captureNoError &&
          b == CaptureErrors.captureNoError) {
        setState(() {});
      }
      _timer?.cancel();
      _timer = Timer.periodic(Duration(milliseconds: 200), (Timer timer) {
        listener();
      });

    }
  }

  void listener() async {
    print("listener");
    SoLoudCapture.instance.getCaptureAudioTexture2D(audioData);
    print(audioData);
  }

```

startRecording is executed on a ButtonPress.
And all i get is this "Pointer with an adress" like `address=0x7fa925708ce0` but no other values.
So maybe i made some mistake in the initialization prozess and there is no "inputsignal"?

**Comment by alnitak** [comment]
You are actually printing the `Pointer` which is addressing the first cell of memory where data is stored. 
You should consider `audioData` as a `List<double>` type. So instead of
`print(audioData);`

to print audio data you have to do 
`for (var i=256; i<512; i++) print(audioData.value[i]);`

**Comment by synchronisator** [comment]
No, sorry, think this is a problem of the pitch detector. Ignore my last comment :D

**Comment by synchronisator** [comment]
I think this is a problem of the "small chunk" of 256 bytes. If i sing a lower note the detector has too little data to detect it. So maybe a bigger chunk could solve this... i will test it :)

**Comment by synchronisator** [comment]
I try to understand, what i have to do to get a correct pitchdetection. One Question is the direction of values i get from the pointer.
is it
[
 [little ago, now], // index 0
 [long ago, little ago], // index 1
 [longer ago, long ago] // index 2
]
is this correct?

**Comment by alnitak** [comment]
Yes, that's correct.
Every time you call `getCaptureAudioTexture2D` a new row (of 512 floats) is stored at index 0 and the previous rows are shifted by one.

**Comment by synchronisator** [comment]
Hi, another question. I need the samplerate is it possible to set or get the used samplerate? like mentioned here: https://github.com/mackron/miniaudio/issues/132
thanks

**Comment by alnitak** [comment]
Samplerate is set by default to 44100 with 2 channels in the init function. There is not yet a way to pass these parameters.
