### ISSUE TITLE
perf: Ability to play precise sound sequences

### ISSUE THREAD

**Issue by LeventeAsztalos** [alnitak/flutter_soloud#78]
**Description**

When I tried to play sharp short sounds very quickly I noticed that the distance between the sounds are not constant, they get messy. A quick way to test this is with the example project, is to replace  'assets/audio/explosion.mp3'  to this [Rimshot1.wav.zip](https://github.com/alnitak/flutter_soloud/files/15036372/Rimshot1.wav.zip) and play them every 100ms. 

```
  Future<void> playTenTimes() async {
    for (int i = 0; i < 20; ++i) {
      await Future.delayed(const Duration(milliseconds: 100));
      await playAnotherInstance();
    }
  }
```
I know this package is not a music sequencer, but it would be awesome, if we could use it for that as well. In the SoLoud documentation I found that `Soloud.playClocked()` addresses something similar, but I am not sure it is the same issue.

**Comment by alnitak** [comment]
Hi @LeventeAsztalos, thanks for your findings.

I did some experiments using `Soloud.play()` and `Soloud.playClocked()`.
On C side I wrote a thread which plays your given sample 200 times. The result is this:
![2024-04-20_13-46](https://github.com/alnitak/flutter_soloud/assets/192827/7a2dffd0-0b63-4338-b36d-e711629bc380)

The upper graph is made using `Soloud.playClocked()`, the bottom with `Soloud.play()` with a microseconds scale.
As you can see there are a lot of delays around 40ms which is the buffer length as stated in `Soloud.playClocked()` doc:
> Note that if your "physics time" granularity is low, playClocked is not really useful. Audio buffers tend to be 40ms long at most.

To test this, I used this code on C side:
```cpp
ActiveSound *sound = sounds[0].get();
std::thread th(
    [sound, time, this]
    {
        for (int i = 0; i < 200; i++)
        {
            std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
            this->soloud.playClocked(time, *sound->sound.get());
            // this->soloud.play(*sound->sound.get());
            usleep(time*1000000);
            std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
            std::cout << std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count() << std::endl;
        }
    });
th.detach();
```
There is no much difference doing the same on Flutter side with a code similar to yours. So the problem could be on SoLoud lib, but as you stated, the lib is not meant to be used as a music sequencer.

I have to investigate further, maybe there is some compiler args to pass or some other tips I missed.

**Comment by alnitak** [comment]
Digging further I tried lowering the buffer size to 512 instead of 2048 (which stores the previously mentioned 40ms).
This is the result:

![2024-04-20_17-48](https://github.com/alnitak/flutter_soloud/assets/192827/69acf826-9bbf-46c2-9a75-56825556a681)

There is not much difference between `playClocked()` and `play()`, anyway some better results.

Currently is not possible to change player initializing parameters, but you can try to manually modify it [here](https://github.com/alnitak/flutter_soloud/blob/d84f46696769d3ce18e69b08214117beb2942d77/src/player.cpp#L34)

**Comment by LeventeAsztalos** [comment]
Thanks for the quick and detailed analysis!  I tried with 512 buffer size, and the result were much better. It would be nice if we could set these params from the flutter side. On the other hand with this approach there will always be some latency. My original problem is not related to the package itself, it rather a technical method question, so I close this issue.

**Comment by zikajk** [comment]
@LeventeAsztalos Why do you think it should not be configurable from this package. And what do you mean there will always be latency? 
Reducing the buffer really does give MUCH better results, so I think it would make sense for some cases. And it seems to me that MINIAUDIO should handle realtime audio with low latency.

**Comment by zikajk** [comment]
@LeventeAsztalos Why do you think it should not be configurable from this package. And what do you mean by there will always be latency? 

When I change it to 0, it's almost perfect (but sometimes it skips, something I have to look at). 
As soon as I change it to anything, I start getting a CPP warning in the console, so maybe a proper configuration / check from this library would make sense?

**Comment by zikajk** [comment]
@alnitak I accidentally deleted the original message, sorry. 
(I was wondering if it makes sense to set the "buffer" in this library (maybe together with sample-rate?)... 

The consequences are clear to me. I'll try to find out how the old trackers solved it. I wanted to make something like ProTracker, with stable 60fps in Flutter we have a very similar starting position as the Amiga had.

**Comment by lukepighetti** [comment]
Feels like this should still be open since it's not resolved 😄

**Comment by kelegorm** [comment]
Hi! I was trying to do that and described that in another issue, [here](https://github.com/alnitak/flutter_soloud/issues/100#issuecomment-2645870833). Long story short, you have to use buffer callback and fill audio buffer sample by sample, and start metronome tick at some sample, mostly not first one.
