### ISSUE TITLE
Play and seek multiple sounds at the same time.

### ISSUE THREAD

**Issue by ismailcaakir** [alnitak/flutter_soloud#9]
Hello,

I was very excited when I saw your library. Thank you very much for your improvements.

I have read your documentation and tried to understand it.

If I can, I have a question for you. 

My application is an MP3 splitter, (splitting music into vocal, drum, bass, piano etc.)

All my media are the same length. I choose vocal.mp3 as the main sound and play the other sounds over this mp3 file (I use just_audio now). 

My general problem here is that if I want to fast forward the song with the slider, there is a synchronization problem. Can I rewind the songs to the same seconds simultaneously with your library or is your library compatible for my project?

I am very sorry for taking your time but I have been trying to solve this synchronization problem for the last 3 days.

<img width="524" alt="Ekran Resmi 2023-08-29 01 04 53" src="https://github.com/alnitak/flutter_soloud/assets/8665190/bc947e17-d75a-4d45-aff8-c5b9741f0e39">

**Comment by alnitak** [comment]
Hi @ismailcaakir 
If I understand correctly you haven't tried this plugin yet?
Anyway, I think there will be no synchronization problems when seeking more the one track. I didn't tried, but I think the problem you have is due to the audio buffering or some latency the plugin has. 
This plugin load the sounds in memory and there shouldn't be any buffering problems.

So you could try with something like:
```
/// Start audio engine if not already
if (!SoLoud().isIsolateRunning()) {
  await SoLoud().startIsolate();
}
/// load the audio files
SoundProp? voice = await SoloudTools.loadFromFile(voiceFile); // or any other load* methods
SoundProp? drum = await SoloudTools.loadFromFile(drumFile);

/// play them
final voiceRet = await SoLoud().play(voice!);
final drumRet = await SoLoud().play(drum!);
```
then in your slider callback do seek both audios:
```
SoLoud().seek(voiceRet!.handle.first, [sliderValue]);
SoLoud().seek(drumFile!.handle.first, [sliderValue]);
```

As I said, I didn't tried this, so please let me know! :)

**Comment by ismailcaakir** [comment]
Hello again,

I tried to integrate your library into my project all day yesterday, I ran my project with the examples you gave. I tested it for about 1 hour and I didn't see any sync problem. So it works great for me. Thank you very much for your reply and for developing this great library. 

```
I may have a few suggestions;

-- It would be great to be able to listen the position value of any sound (I had to use a timer, you developed it this way in your examples) [https://github.com/alnitak/flutter_soloud/blob/main/example/lib/page_multi_track.dart](url)

-- It would be great to play multiple songs on one player (this is so fantastic 😄  )

-- We may need to work a little more for the documents. When I first read it, I was very scared if I could use it 😄  (I will try to send PR for this issue at the first available moment)
```

Have a nice days!

**Comment by alnitak** [comment]
@ismailcaakir  I am happy to know that it works great!!

> -- It would be great to be able to listen the position value of any sound (I had to use a timer, you developed it this way in your examples)
I thought about this, but I went ahead letting the dev implement it. Anyway I am putting this in my TODOs

> -- It would be great to play multiple songs on one player (this is so fantastic 😄  )
yes, this is nice :). If I remember correctly, there could be 32 simultaneous sounds which the SoLoud lib author has set as a limit. But it can be raised.

> -- We may need to work a little more for the documents. When I first read it, I was very scared if I could use it
I am aware of being a TERRIBLE doc writer 😄 but I know that the first impression determines the willingness to use the plugin.

Anyway, if you like to know how the plugin works, you could take a look at the SoLoud documentation [here](https://solhsa.com/soloud/index.html)

My best

**Comment by ismailcaakir** [comment]
Again, I am grateful for bringing this great plugin to the community.

Best Regards.
