### ISSUE TITLE
feat: Implement setInaudibleBehavior()

### ISSUE THREAD

**Issue by sbauly** [alnitak/flutter_soloud#96]
**Description**

By default, if a sound is inaudible, it's paused, and will resume when it becomes audible again. If you want an inaudible sound to keep playing whilst muted, SoLoud's solution is to use [Soloud.setInaudibleBehavior()](https://solhsa.com/soloud/attributes.html)

It would be great if we could implement this method into flutter_soloud.

**Requirements**

- [ ]  Introduce `void setInaudibleBehavior(bool aMustTick, bool aKill);`

**Comment by sbauly** [comment]
Hi @alnitak, any updates on this?

I tried having a go at generating the bindings myself, but unfortunately have had issues locally!

**Comment by alnitak** [comment]
Oh yes! After the #156 I will!

**Comment by alnitak** [comment]
Hi @sbauly,

I made PR #160 which implements the `setInaudibleBehavior`. But if I understand correctly, this is only for 3D audio.
Please, take a look at the PR description for more info and an example.

**Comment by sbauly** [comment]
I just tested the feature using the `inaudible_behavior` branch, and it's working perfectly!

Thanks so much @alnitak ! I will close the issue now.

This is a very useful feature for keeping multiple sounds in time with one another, even when some sounds aren't currently needed, but may need to be heard later.

**Comment by alnitak** [comment]
Thanks for telling me!! And sorry for the long wait, I completely forgot :)
