### ISSUE TITLE
feat: set relative speed without changing the pitch

### ISSUE THREAD

**Issue by orestesgaolin** [alnitak/flutter_soloud#98]
**Description**

I would like to change the relative speed of the playing sound without affecting the pitch, similar to [tempo change in Audacity](https://manual.audacityteam.org/man/change_speed.html) or YouTube player speed.

**Requirements**

- [ ] A way to change audio speed/tempo without changing the pitch of the audio

**Additional Context**

Currently the `setRelativePlaySpeed` changes the pitch if you change the speed

**Comment by alnitak** [comment]
Thanks @orestesgaolin, I see this is somewhat feasible, so there is a good chance to have this functionality after having the pitch feature.

I'll take a look soon.

**Comment by alnitak** [comment]
Hi @orestesgaolin,

It took a bit long to overcome this, there were big improvements around. But I think your request could be satisfied!

In the `pitch` branch, you will find implemented the new `PitchShift` filter and a new way to manage filters for single sounds or for the global output. There is an example in `lib/filters/sound_filter.dart` to set the relative play speed without changing the pitch. The trick is to set the shift filter parameter to "1/speed".

Soon we will merge and publish to pub.dev.

**Comment by orestesgaolin** [comment]
That _sounds_ amazing, I'll play with that as soon as possible
